services:
    cb.table_calendar_events_tags.permission:
        class: BlackForest\Contao\Calendar\Tags\EventListener\Table\CalendarEventsTags\Permission
        public: true
        arguments:
            - "@contao.framework"
            - "@request_stack"
            - "@session"
            - "@=service('contao.framework').getAdapter('Contao\\\\StringUtil')"
            - "@=service('contao.framework').getAdapter('Contao\\\\Input')"
            - "@=service('contao.framework').getAdapter('Contao\\\\Controller')"
            - "@=service('contao.framework').getAdapter('Contao\\\\Image')"

    cb.table_calendar_events_tags.calendar_options:
        class: BlackForest\Contao\Calendar\Tags\EventListener\Table\CalendarEventsTags\CalendarOptions
        public: true
        arguments:
            - "@contao.framework"
            - "@request_stack"
            - "@=service('contao.framework').getAdapter('Contao\\\\NewsArchiveModel')"

    cb.table_calendar_events_tags.alias_generator:
        class: BlackForest\Contao\Calendar\Tags\EventListener\Table\CalendarEventsTags\AliasGenerator
        public: true
        arguments:
            - "@database_connection"
            - "@=service('contao.framework').getAdapter('Contao\\\\StringUtil')"
