services:
    cb.table_calendar_events_tags_relation.permission:
        class: BlackForest\Contao\Calendar\Tags\EventListener\Table\CalendarEventsTagsRelation\Permission
        public: true
        arguments:
            - "@contao.framework"
            - "@request_stack"
            - "@session"
            - "@=service('contao.framework').getAdapter('Contao\\\\StringUtil')"
            - "@=service('contao.framework').getAdapter('Contao\\\\Input')"
            - "@=service('contao.framework').getAdapter('Contao\\\\Controller')"
            - "@=service('contao.framework').getAdapter('Contao\\\\Image')"

    cb.table_calendar_events_tags_relation.calendar_options:
        class: BlackForest\Contao\Calendar\Tags\EventListener\Table\CalendarEventsTagsRelation\CalendarOptions
        public: true
        arguments:
            - "@contao.framework"
            - "@request_stack"
            - "@database_connection"

    cb.table_calendar_events_tags_relation.calendar_events_options:
        class: BlackForest\Contao\Calendar\Tags\EventListener\Table\CalendarEventsTagsRelation\CalendarEventsOptions
        public: true
        arguments:
            - "@database_connection"

    cb.table_calendar_events_tags_relation.tag_options:
        class: BlackForest\Contao\Calendar\Tags\EventListener\Table\CalendarEventsTagsRelation\TagOptions
        public: true
        arguments:
            - "@database_connection"
