services:
    cb.table_calendar.permission:
        class: BlackForest\Contao\Calendar\Tags\EventListener\Table\Calendar\Permission
        public: true
        arguments:
            - "@contao.framework"
            - "@request_stack"
            - "@=service('contao.framework').getAdapter('Contao\\\\StringUtil')"
            - "@=service('contao.framework').getAdapter('Contao\\\\Controller')"
